version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: github_notes_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_notes
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - github_notes_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_notes_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: github_notes
      DB_SSL_MODE: disable
      JWT_SECRET: your_super_secret_jwt_key_here_please_change_this_in_production
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - github_notes_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  github_notes_network:
    driver: bridge
